sudo: required
dist: trusty

language: go
go: 1.8

install:
  - rvm install 2.4.1
  - bin/setup

script:
  - rake

notifications:
  email: false

before_deploy: bin/cross-compile
deploy:
  api_key:
    secure: MlzNG3UstgOIKG2Ao8TVTxBOg0rrckYVnjvCRz235ZO/oxQvfGKXK/Hw1M3Tuj8MehEcf2qqmG4k1GJ8TuYxuF2MEtnUjE6O6pR7Bjez6g5QisnHIuuO+Ydx9K+O4lcpsXA2L8NB+c4BRCZBJ3PUdpBo8UNoCXCXX/u476tjCq251zTGowdGqhj7s9DVKZS0coqWz4gU6dnyQkPrI7wmSKPwBUbLyESRTSm3T3kIKfl+jCvnLSH3YLzn/Srs3U/Czz1bxFZ7xIAHnm7NoiKf0N7aQzcLA7vdOCKeFgP+3sW0DP/90peFJ7cu6qDqk+r8dySnn6xFB3kPbeSGVUCGL17fcSOMkIGMCBCR7/ofbrblKP/tDHMsAcRJNqb4TdTNle6cotC460Am01dqoy+9rXndgEzrQ5xp6D86Yc9dRvzOb5vK8O8+0iNxVRZ6TvvbWAsHHwSvHLNJtrtTMfLuoLIt/YnDiB98cfJSoDXmxmEMYmYpJRuwjyRTr9sIO7W5rQIMcCoM5ihvXGtOss4EpPazG5/DRs1PfOQdTayFWJxg6c1z1xbPBtwRFTyBdFIKX4/oA6OmIM4yK75qwfbtb+aB5JwvhmZ9+dphudKof1+6lWUQP1sOLKG1bgkNxaoL8bt7QwfDnjIIpj8Wa0ErcFBJ2AlhCHOXzswYy8hheOk=
  file: "dist/*"
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
